export PYENV_ROOT=$HOME/.pyenv
export PATH=$PYENV_ROOT/bin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$HOME/.poetry/bin:.

eval "$(pyenv init --path)"

#$HOME/.local/bin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PYENV_ROOT/bin:$HOME/.poetry/bin:$HOME/bin
