# CI to Docker Hub

on:
  push:
    tags:
        - "v*.*.*"
    
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build zsh
        id: build_zsh
        uses: docker/build-push-action@v2
        with:
          context: ./Docker/zsh
          file: ./Docker/zsh/Dockerfile
          push: true
          tags: seebaktec/zsh:latest

      - name: Build tmux
        id: build_tmux
        uses: docker/build-push-action@v2
        with:
          context: ./Docker/tmux
          file: ./Docker/tmux/Dockerfile
          push: true
          tags: seebaktec/tmux:latest

      - name: Build pyenv
        id: build_pyenv
        uses: docker/build-push-action@v2
        with:
          context: ./Docker/pyenv
          file: ./Docker/pyenv/Dockerfile
          push: true
          tags: seebaktec/pyenv:latest

      - name: Build nvim
        id: build_nvim
        uses: docker/build-push-action@v2
        with:
          context: ./Docker/nvim
          file: ./Docker/nvim/Dockerfile
          push: true
          tags: seebaktec/nvim:latest

      - name: Build pytools
        id: build_pytools
        uses: docker/build-push-action@v2
        with:
          context: ./Docker/pytools
          file: ./Docker/pytools/Dockerfile
          push: true
          tags: seebaktec/pytools:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
